name: Docs

on:
  push:
    branches: [master]
    paths:
      - docs/**
  # workflow_dispatch: {}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        working-directory: docs
        run: yarn install

      - name: Generate docs
        working-directory: docs
        run: yarn generate

      - name: Publish to GH pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/dist
