name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  
  # Check build
  build:
    
    runs-on:
      ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [17, 16] # latest & recommended
    
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Linting
        run: npm run lint
      
      - name: Testing
        run: npm run test
  
  # Create release
  release:
    
    needs: build
    
    runs-on:
      ubuntu-latest
    
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
